alias ..='cd ..'
alias ...='cd ../..'
alias ....='pushd . && cd ../../..'
alias .....='pushd . && cd ../../../..'
alias ......='pushd . && cd ../../../../..'
alias pv='p4v'
alias vim='vim -p'
alias pv='p4v&'
