  (set-fontset-font t 'hangul (font-spec :name "Noto Serif CJK KR SemiBold"))

  (if (daemonp)
      (progn
  	(add-hook 'after-make-frame-functions
  		  (lambda (frame)
  		    (with-selected-frame frame
  		      (set-fontset-font "fontset-default" '(#x1100 . #x11ff)
  					'("Noto Serif CJK KR SemiBold". "iso10646-1"))
  		      (set-fontset-font "fontset-default" '(#x302e . #x318f)
  					'("Noto Serif CJK KR SemiBold". "iso10646-1"))
  		      (set-fontset-font "fontset-default" '(#x3200 . #x321e)
  					'("Noto Serif CJK KR SemiBold". "iso10646-1"))
  		      (set-fontset-font "fontset-default" '(#x3260 . #x327f)
  					'("Noto Serif CJK KR SemiBold". "iso10646-1"))
  		      (set-fontset-font "fontset-default" '(#xa960 . #xa97f)
  					'("Noto Serif CJK KR SemiBold". "iso10646-1"))
  		      (set-fontset-font "fontset-default" '(#xac00 . #xd7ff)
  					'("Noto Serif CJK KR SemiBold". "iso10646-1"))
  		      (set-fontset-font "fontset-default" '(#xffa0 . #xffdc)
  					'("Noto Serif CJK KR SemiBold". "iso10646-1"))
  		      ;; (set-fontset-font "fontset-default" '(#xe0bc . #xf66e)
  		      ;; 			'("Noto Serif CJK KR SemiBold". "iso10646-1"))
  		      )))
  	)
    (set-fontset-font "fontset-default" '(#x1100 . #x11ff)
		      '("Noto Serif CJK KR SemiBold". "iso10646-1"))
    (set-fontset-font "fontset-default" '(#x302e . #x318f)
		      '("Noto Serif CJK KR SemiBold". "iso10646-1"))
    (set-fontset-font "fontset-default" '(#x3200 . #x321e)
		      '("Noto Serif CJK KR SemiBold". "iso10646-1"))
    (set-fontset-font "fontset-default" '(#x3260 . #x327f)
		      '("Noto Serif CJK KR SemiBold". "iso10646-1"))
    (set-fontset-font "fontset-default" '(#xa960 . #xa97f)
		      '("Noto Serif CJK KR SemiBold". "iso10646-1"))
    (set-fontset-font "fontset-default" '(#xac00 . #xd7ff)
		      '("Noto Serif CJK KR SemiBold". "iso10646-1"))
    (set-fontset-font "fontset-default" '(#xffa0 . #xffdc)
		      '("Noto Serif CJK KR SemiBold". "iso10646-1"))
    )
