(add-to-list 'custom-theme-load-path "~/.emacs.d/theme")
;;(require 'airline-themes)
;;(load-theme 'airline-papercolor t)
;;(require 'color-theme-sanityinc-tomorrow)
(load-theme 'paper t)
;; (load-theme 'blackboard t)
;; (defun my-sanityinc-tomorrow-bright ()
;;   (interactive)
;;   (color-theme-sanityinc-tomorrow--define-theme bright)
;;   )
;;(my-sanityinc-tomorrow-bright)
