(require 'cc-mode)
(require 'semantic)

(global-semanticdb-minor-mode 1)
(global-semantic-idle-scheduler-mode 1)
(global-semantic-decoration-mode 1)
(global-semantic-highlight-func-mode 1)
(global-semantic-idle-completions-mode 1)
(global-semantic-stickyfunc-mode 1)
(global-semantic-idle-summary-mode 1)

(semantic-mode 1)
;;(semantic-add-system-include "/usr/include/boost" 'c++-mode)
;;(semantic-add-system-include "~/linux/kernel")
;;(semantic-add-system-include "~/linux/include")
