#!/bin/bash
set -e
PATH="/usr/local/bin:$PATH"
cd "$(git rev-parse --show-toplevel 2>/dev/null)"
rm -f GTAGS GRTAGS GPATH
git ls-files | grep -F .c 2>/dev/null
if [[ $? == 0 ]]
then
  git ls-files | gtags -v -i -f -
fi
